### ISSUE TITLE
accessories structure for leak sensor 

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/esp-homekit-air-quality-sensor#10]
Hi,

I want to customize your air quality sensor adding water leak sensor. Could you help me that how it should be?

```
homekit_accessory_t *accessories[] = {
    HOMEKIT_ACCESSORY(.id=1, .category=homekit_accessory_category_sensor, .services=(homekit_service_t*[]){
        HOMEKIT_SERVICE(ACCESSORY_INFORMATION, .characteristics=(homekit_characteristic_t*[]){
            &name,
            &manufacturer,
            &serial,
            &model,
            &revision,
            HOMEKIT_CHARACTERISTIC(IDENTIFY, identify),
            NULL
        }),
        HOMEKIT_SERVICE(TEMPERATURE_SENSOR, .primary=true, .characteristics=(homekit_characteristic_t*[]){
            HOMEKIT_CHARACTERISTIC(NAME, "Temperature Sensor"),
            &current_temperature,
            NULL
        }),
        HOMEKIT_SERVICE(HUMIDITY_SENSOR, .primary=true, .characteristics=(homekit_characteristic_t*[]){
            HOMEKIT_CHARACTERISTIC(NAME, "Humidity Sensor"),
            &current_relative_humidity,
            NULL
        }),
        HOMEKIT_SERVICE(AIR_QUALITY_SENSOR, .primary=true, .characteristics=(homekit_characteristic_t*[]){
            HOMEKIT_CHARACTERISTIC(NAME, "Air Quality Sensor"),
            &air_quality,
            &ozone_density,
            &nitrogen_dioxide_density,
            &sulphur_dioxide_density,
            &pm25_density,
            &pm10_density,
            &carbon_monoxide_level,
            &lpg_level,
            &methane_level,
            &ammonium_level,
            &ota_trigger,
            &wifi_reset,
            &wifi_check_interval,
            NULL
        }),
        NULL
    }),
    NULL
};
```

**Comment by maccoylton** [comment]
Which specific leak sensor do you  want to add?

**Comment by okanduzyel** [comment]
https://cdn.macrumors.com/article-new/2019/06/homekitnewaccessoryicons-800x772.jpg

(It's icon shown at left side)

Could you provide a simple example for leak sensor like motion sensor example?

**Comment by okanduzyel** [comment]
I have defined it like that:

```
#define LEAK_SENSOR_GPIO 4

homekit_characteristic_t leak_detected  = HOMEKIT_CHARACTERISTIC_(LEAK_DETECTED, 0);
```


then, I added that to structure:

```
        HOMEKIT_SERVICE(LEAK_SENSOR, .primary=true, .characteristics=(homekit_characteristic_t*[]){
            HOMEKIT_CHARACTERISTIC(NAME, "Leak Sensor"),
            &leak_detected,
            NULL
        }),
        NULL
```

In GPIO init:

```
    gpio_enable(LEAK_SENSOR_GPIO, GPIO_INPUT);
    gpio_set_pullup(LEAK_SENSOR_GPIO, false, false);
    gpio_set_interrupt(LEAK_SENSOR_GPIO, GPIO_INTTYPE_EDGE_ANY, leak_sensor_callback);
```

lastly:

```
void leak_sensor_callback(uint8_t gpio) {
    if (gpio == LEAK_SENSOR_GPIO){
        int new = 0;
        new = gpio_read(LEAK_SENSOR_GPIO);
        leak_detected.value = HOMEKIT_BOOL(new);
        homekit_characteristic_notify(&leak_detected, HOMEKIT_BOOL(new));
    }
    else {
        printf("Interrupt on %d", gpio);
    }
}
```

It can add a leak sensor when it pairs with my home app however when leak pin changes its state, accessory doesn't any response on homekit (crashes)


Do you have any idea?

**Comment by maccoylton** [comment]
Which specific leak sensor do you have? I had a quick look and some of them appear to have an analogue output and others a digital.

**Comment by okanduzyel** [comment]
Digital, like motion sensor. 

Leak detected or not.

**Comment by okanduzyel** [comment]
https://s.click.aliexpress.com/e/sF5efH5Z

You can simply implement digital output with logic opamp, if you have analog leak sensor. If you don’t want, you can order that kind of sensors.

**Comment by maccoylton** [comment]
did you ever get this fixed?

**Comment by okanduzyel** [comment]
Sorry for late answer. Unfortunately I couldn't...

**Comment by maccoylton** [comment]
>https://cdn.macrumors.com/article-new/2019/06/homekitnewaccessoryicons-800x772.jpg ...

@okanduzyel each device requires coding specific to the make a
>Sorry for late answer. Unfortunately I couldn't... 

@okanduzyel if it’s digital on/off output then my motion sensor example would actually work without

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by okanduzyel** [comment]
> digital on/off output then my motion sensor example would actually work without

It was sticking when leak sensor pin's logic level changed. I had just modified motion sensor example. I think structure must have been different or needed more code to identify leak sensor.

**Comment by maccoylton** [comment]
>> digital on/off output then my motion sensor example would actually work without ...

@okanduzyel look forward to seeing your code 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
