### ISSUE TITLE
air-quality-sensor can only measure pm10

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/esp-homekit-air-quality-sensor#11]
It can only measure pm10 density. Is it normal?

That is what it looks on my home:

https://i.imgyukle.com/2019/11/30/RjRP4y.png

**Comment by maccoylton** [comment]
>It can only measure pm10 density. Is it normal? ...

@okanduzyel try it near a car exhaust or a lighted candle or match, you should see  other readings. Even breathing g on it heavily will show variations 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by okanduzyel** [comment]
Thanks for your reply. I will try. 

Besides, 140k resistor does not fit correctly values for me. 

180k is okay.

Addition: Eve app is so nice to see all variation of parameters. On the other hand, apple's home app is too poor.

**Comment by maccoylton** [comment]
Did you re-test and was it ok?

**Comment by okanduzyel** [comment]
Sorry for late answer. 

Yes! It works correctly. 👍🏻

**Comment by maccoylton** [comment]
no worries 👍
