### ISSUE TITLE
error reading flash

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/esp-homekit-air-quality-sensor#12]
Hi,

I face off that issue after the OTA configuration.

```
send request......OK
erasing@0x6b000>2d6f70...00004d  so far collected 430144 bytes
--- ota_verify_hash
--- ota_hash
error reading flash
error reading flash
```

**Comment by maccoylton** [comment]
Try latest version

**Comment by okanduzyel** [comment]
> Try latest version

I guess I use the latest version. (Downloaded them from your links)

```
--- ota_connect
target IP is 185.199.109.154 bind socket 62008....OK. socket connect to remote....OK. create SSL....OK. set_fd done. SSL to github-releases.githubusercontent.com port 443....failed, return [-0x1]
wolfSSL_send error = -322
send request......failed, return [-0x1]
wolfSSL_send error = -322
--- ota_verify_hash
--- ota_hash
error reading flash
error reading flash
```

**Comment by maccoylton** [comment]
Due to this error _"wolfSSL_send error = -322"_, you need to update the bootloader with a serial connection. This was out-with my control, and to do with the way LCM works with GitHub.

**Comment by okanduzyel** [comment]
I downloaded three files that you gave and programmed with the serial port.

`esptool.py -p /dev/cu.usbserial-1420 --baud 230400 write_flash -fs 8m -fm dout -ff 40m 0x0 rboot.bin 0x1000 blank_config.bin 0x2000 otaboot.bin`

**Comment by maccoylton** [comment]
Apologies, Wiki was out of date. Try again with latest Wiki instructions.

**Comment by okanduzyel** [comment]
Now it is LCM-XXXXXX. Connected via wifi but doesn't show pop-up setup page.

**Comment by maccoylton** [comment]
I assume you erase the flash prio to flashing the bootloader, this can happen, two options 

- retry until it comes up
- enter the details through the command line. 

I develop on a Mac, so I use pio

pio device monitor --port $ESPPORT --baud 115200

you can then type all the details directly form the command line.

**Comment by okanduzyel** [comment]
Flashed again and it solved. But,

- select your WiFi by clicking on it
- enter your WiFi password
- enter the GitHub directory - **maccoylton/eps-homekit-motion-sensor**
- enter filename - main.bin.
- click the join button

It must be **/maccoylton/esp-homekit-air-quality-sensor** I think your wiki must upgrade a little bit.

**Comment by maccoylton** [comment]
thanks, updated to correct spelling
