### ISSUE TITLE
Support Extensions

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/esp-homekit-air-quality-sensor#13]
Hi @maccoylton,

Could you support extensions for this project? So, air-quality-sensor can send notification when the air is polluted.

**Comment by maccoylton** [comment]
This would be done with on the IOS device and not the accessory.. The accessory will send a notification to the IOS device when the air quality changes, it is then up to the IOS device to handle that change and notify as appropriate. I would recommend looking at the Eve app, you can create automations on sensors from there.

**Comment by okanduzyel** [comment]
I was meaning like that: https://www.youtube.com/watch?v=fyfqdIVZfdk
