### ISSUE TITLE
value showed

### ISSUE THREAD

**Issue by lizzus** [maccoylton/esp-homekit-air-quality-sensor#3]
with display monitor I saw that mq135 found this value:
air quality
Rs
CO
LPG
PM10
methane
NH4
but in homekit we have:

air_quality  --> OK
ozone density	 --> not possible with MQ135 but with MQ131 sensor
nitrogen dioxide (NO 2) density --> not possible with MQ135 but with MQ136 sensor
sulphur_dioxide (E 220) density  --> not possible with MQ135
PM25 density	 --> not possible with MQ135
PM10 density OK
carbon monoxide_level OK

is possibile display on homekit LPG, methane and NH4 value?

**Comment by maccoylton** [comment]
this would require adding custom characteristics.. which can be done when time permits

**Comment by lizzus** [comment]
can be updated with OTA. I hope you will add! :-)

**Comment by lizzus** [comment]
I see you updated with a new release. What's new?

**Comment by maccoylton** [comment]
Just added the extra characteristics requested above, doing final test of flashing OTA. Will update the main page shortly

**Comment by lizzus** [comment]
I updated and i can see value on EVE (not in home app)

**Comment by lizzus** [comment]
thanks for your great work!

**Comment by lizzus** [comment]
can you create a rain sensor with this arduino accessory? 
![71CfnB5V-SL _SL1500_](https://user-images.githubusercontent.com/8824834/57251197-805cce00-7049-11e9-9acb-ad2803c2dd9f.jpg)

**Comment by maccoylton** [comment]
Most anything is possible if you put your mind to it ;-)

**Comment by lizzus** [comment]
> Most anything is possible if you put your mind to it ;-)

Yes, is true!
