### ISSUE TITLE
Led connection

### ISSUE THREAD

**Issue by lizzus** [maccoylton/esp-homekit-air-quality-sensor#5]
1. When led connected to GPIO13 ligth on?
2. You wrote I need to use a resistor for led. Can you make a little schema for led connection please?. Thanks.

**Comment by maccoylton** [comment]
The resistor is inline to the led. it doesn't matter if you put it before or after the led. So either :-

+3.3v -> resistor -> led -> GPIO13
OR
+3.3v -> led  -> resistor -> GPIO13 

will work

**Comment by lizzus** [comment]
thank you so much. How many  K?

**Comment by maccoylton** [comment]
>thank you so much. How many  K?

@lizzus it depends on the LED, would suggest minimum of 50 ohms. If you use too lie, the LED will blow, too high and it will be dull or nit light at all. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lizzus** [comment]
when light on?

**Comment by lizzus** [comment]
I mean deafult led light is off and light on when value chenge to poor or is always light on?

**Comment by maccoylton** [comment]
LED will come on if there is an error reading the sensor or if the identify function is triggered form within the EVE app

**Comment by lizzus** [comment]
Maybe i not understand how to connect it. I connected: 
![schema](https://user-images.githubusercontent.com/8824834/57575126-46bf0500-7445-11e9-8879-ce5c5d93deb7.jpg)
Is correct? I ask because led is always light on.

**Comment by lizzus** [comment]
Ok, My last connection was wrong. Now i connect correctly and if i press "ID" on EVE App LED light on.
I tried to disconnect sensor for see if led light, but not light...

**Comment by maccoylton** [comment]
>Ok, My last connection was wrong. Now i connect correctly and if i press "ID" on EVE App LED light on. ...

@lizzus it will only react to the temperate/ humidity sensor being unplugged.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lizzus** [comment]
ahh ok. YES, it's true! I unplugged and light on :-)

**Comment by lizzus** [comment]
I have a suggestion: connection of a relay! When value are poor this change from NC to NO.

**Comment by maccoylton** [comment]
>I have a suggestion: connection of a relay! When value are poor this change from NC to NO.

@lizzus what would the relay be used for ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lizzus** [comment]
this is my contact. lizzus[at]me.com Please write me and after delete this post. :-)
