### ISSUE TITLE
Schematics request

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/esp-homekit-air-quality-sensor#8]
Hi,

Words are sometimes misunderstanding things.

So, could you support your explanation which is below with schematics please?

"The anlaogue output of the MQ135 is connected to the anlog input of you ESP module. If you are using a nodeMCU or Weemos D1 these have a built in voltage divider on the analogue input which scales 3.3v to 1v, so you need to connect a 180k resistor inline betwen the sensor and the anlogue input pin to allow this to scale From 5v to 1v. If you are connecting directly to a bare ESP8266 chip, then you need to add a voltage divider between the sensor and the analog input to scale form 5v to 1v."

**Comment by maccoylton** [comment]
Added Fritzing
