### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/esp-homekit-air-quality-sensor#9]
Hi,

I cloned correctly your files into my vagrant-ubuntu machine but, inside of src file make commands don't work as I listed a below. 

```
make -C . all
make -C . test
make -C . erase_flash
```

Other Maxim Kulkin examples can build and flash. Can you check it please?

**Comment by maccoylton** [comment]
>Hi, ...

@okanduzyel can you provide a log, it obviously works for me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by okanduzyel** [comment]
> > Hi, ...
> 
> @okanduzyel can you provide a log, it obviously works for me
> 
> Sent with [GitHawk](http://githawk.com)

I didn't understand what you mean 🙁

**Comment by maccoylton** [comment]
execute the commands and capture the output you get

BTW I use :-

make clean 
make 
make flash

**Comment by okanduzyel** [comment]
vagrant@vagrant-ubuntu-trusty-64:~/esp-homekit-demo/examples/esp-homekit-air-quality-sensor/src$ ### make flash
/home/vagrant/esp-open-rtos/common.mk:223: /home/vagrant/esp-homekit-demo/examples/esp-homekit-air-quality-sensor/components/esp-homekit-common-functions/shared_functions/component.mk: No such file or directory
make: *** No rule to make target `/home/vagrant/esp-homekit-demo/examples/esp-homekit-air-quality-sensor/components/esp-homekit-common-functions/shared_functions/component.mk'.  Stop.

**Comment by okanduzyel** [comment]
vagrant@vagrant-ubuntu-trusty-64:~/esp-homekit-demo/examples/esp-homekit-air-quality-sensor/src$ **make flash**
/home/vagrant/esp-open-rtos/common.mk:223: /home/vagrant/esp-homekit-demo/examples/esp-homekit-air-quality-sensor/components/esp-homekit-common-functions/shared_functions/component.mk: No such file or directory
make: *** No rule to make target `/home/vagrant/esp-homekit-demo/examples/esp-homekit-air-quality-sensor/components/esp-homekit-common-functions/shared_functions/component.mk'.  Stop.

> execute the commands and capture the output you get
> 
> BTW I use :-
> 
> make clean
> make
> make flash

**Comment by maccoylton** [comment]
Looks like you have not pulled all the required libraries form GitHub. Go to directory /home/vagrant/esp-homekit-demo/examples/esp-homekit-air-quality-sensor/components/  and execute command  "git submodule update --init --recursive". The clue is in the error above where it tell you it can't find the file _"No such file or directory"_.

**Comment by okanduzyel** [comment]
It didn't work. I have got your example with that code. 

**git clone --recursive https://github.com/maccoylton/esp-homekit-air-quality-sensor.git .**

other examples which I found on internet can build just cloning but yours didn't work.




Addition: Could you try to clone your example to new ubuntu machine?

**Comment by maccoylton** [comment]
I develop on MacOS, I do not use nor have access to unbubtu.  Per the error above the issue is you do not have all the submodules in place. Please ensure you initialise all the submodules, then it will build fine. 

You need to ensure you have:- 

UDPlogger
esp-adv-buton
esp-homekit
esp-cjson
esp-homekit-common-functions
esp-wolfssl
esp-wifi-config 

in the components subdirectory as per GitHub

**Comment by maccoylton** [comment]
Hi there was an issue with the version of esp-homekit-common-functions, try now

**Comment by okanduzyel** [comment]
Now, It is okay. Thank you so much 🙂
